### PR TITLE
Simplify example in docs

### PR DESCRIPTION
**Pull request by benmccann**
Fixes https://github.com/cardillo/joinery/issues/64

### CODE REVIEW

**Comment by benmccann** [comment]
@cardillo could you merge this?

**Comment by cardillo** [comment]
The changes look good, but need to deprecate java 7 support first.

**Comment by benmccann** [comment]
@cardillo can this one be merged now that Java 7 support has been dropped?

**Comment by cardillo** [comment]
@benmccann Done! Thanks.

**Pull request merged**
